package entidades;
// Generated 22-abr-2019 23:38:06 by Hibernate Tools 4.3.1



/**
 * EstadoAlquiler generated by hbm2java
 */
public class EstadoAlquiler  implements java.io.Serializable {


     private Integer id;
     private String nombre;

    public EstadoAlquiler() {
    }

    public EstadoAlquiler(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


