package entidades;
// Generated 28-abr-2019 23:19:03 by Hibernate Tools 4.3.1



/**
 * Estadoalquiler generated by hbm2java
 */
public class Estadoalquiler  implements java.io.Serializable {


     private Integer id;
     private String nombre;

    public Estadoalquiler() {
    }

    public Estadoalquiler(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


