package entidades;
// Generated 22-abr-2019 23:38:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Incidencia generated by hbm2java
 */
public class Incidencia  implements java.io.Serializable {


     private Integer id;
     private Alquiler alquiler;
     private Cliente cliente;
     private TipoIncidencia tipoIncidencia;
     private String descripcion;
     private Integer posicionLat;
     private Integer posicionAlt;
     private Set imagens = new HashSet(0);

    public Incidencia() {
    }

	
    public Incidencia(Cliente cliente, TipoIncidencia tipoIncidencia) {
        this.cliente = cliente;
        this.tipoIncidencia = tipoIncidencia;
    }
    public Incidencia(Alquiler alquiler, Cliente cliente, TipoIncidencia tipoIncidencia, String descripcion, Integer posicionLat, Integer posicionAlt, Set imagens) {
       this.alquiler = alquiler;
       this.cliente = cliente;
       this.tipoIncidencia = tipoIncidencia;
       this.descripcion = descripcion;
       this.posicionLat = posicionLat;
       this.posicionAlt = posicionAlt;
       this.imagens = imagens;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Alquiler getAlquiler() {
        return this.alquiler;
    }
    
    public void setAlquiler(Alquiler alquiler) {
        this.alquiler = alquiler;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public TipoIncidencia getTipoIncidencia() {
        return this.tipoIncidencia;
    }
    
    public void setTipoIncidencia(TipoIncidencia tipoIncidencia) {
        this.tipoIncidencia = tipoIncidencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getPosicionLat() {
        return this.posicionLat;
    }
    
    public void setPosicionLat(Integer posicionLat) {
        this.posicionLat = posicionLat;
    }
    public Integer getPosicionAlt() {
        return this.posicionAlt;
    }
    
    public void setPosicionAlt(Integer posicionAlt) {
        this.posicionAlt = posicionAlt;
    }
    public Set getImagens() {
        return this.imagens;
    }
    
    public void setImagens(Set imagens) {
        this.imagens = imagens;
    }




}


