package entidades;
// Generated 28-abr-2019 23:19:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mantenimiento generated by hbm2java
 */
public class Mantenimiento  implements java.io.Serializable {


     private Integer id;
     private Scooter scooter;
     private Date fechaInicio;
     private Date fechaFin;
     private Set incidencias = new HashSet(0);

    public Mantenimiento() {
    }

	
    public Mantenimiento(Scooter scooter, Date fechaInicio, Date fechaFin) {
        this.scooter = scooter;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }
    public Mantenimiento(Scooter scooter, Date fechaInicio, Date fechaFin, Set incidencias) {
       this.scooter = scooter;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.incidencias = incidencias;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Scooter getScooter() {
        return this.scooter;
    }
    
    public void setScooter(Scooter scooter) {
        this.scooter = scooter;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Set getIncidencias() {
        return this.incidencias;
    }
    
    public void setIncidencias(Set incidencias) {
        this.incidencias = incidencias;
    }




}


