package entidades;
// Generated 28-abr-2019 23:19:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Scooter generated by hbm2java
 */
public class Scooter  implements java.io.Serializable {


     private Integer id;
     private Modelo modelo;
     private String matricula;
     private int codigo;
     private Date fechaCompra;
     private double precioCompra;
     private Integer posicionLat;
     private Integer posicionAlt;
     private Set estadoscooters = new HashSet(0);
     private Set sedes = new HashSet(0);
     private Set mantenimientos = new HashSet(0);

    public Scooter() {
    }

	
    public Scooter(Modelo modelo, String matricula, int codigo, Date fechaCompra, double precioCompra) {
        this.modelo = modelo;
        this.matricula = matricula;
        this.codigo = codigo;
        this.fechaCompra = fechaCompra;
        this.precioCompra = precioCompra;
    }
    public Scooter(Modelo modelo, String matricula, int codigo, Date fechaCompra, double precioCompra, Integer posicionLat, Integer posicionAlt, Set estadoscooters, Set sedes, Set mantenimientos) {
       this.modelo = modelo;
       this.matricula = matricula;
       this.codigo = codigo;
       this.fechaCompra = fechaCompra;
       this.precioCompra = precioCompra;
       this.posicionLat = posicionLat;
       this.posicionAlt = posicionAlt;
       this.estadoscooters = estadoscooters;
       this.sedes = sedes;
       this.mantenimientos = mantenimientos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public double getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(double precioCompra) {
        this.precioCompra = precioCompra;
    }
    public Integer getPosicionLat() {
        return this.posicionLat;
    }
    
    public void setPosicionLat(Integer posicionLat) {
        this.posicionLat = posicionLat;
    }
    public Integer getPosicionAlt() {
        return this.posicionAlt;
    }
    
    public void setPosicionAlt(Integer posicionAlt) {
        this.posicionAlt = posicionAlt;
    }
    public Set getEstadoscooters() {
        return this.estadoscooters;
    }
    
    public void setEstadoscooters(Set estadoscooters) {
        this.estadoscooters = estadoscooters;
    }
    public Set getSedes() {
        return this.sedes;
    }
    
    public void setSedes(Set sedes) {
        this.sedes = sedes;
    }
    public Set getMantenimientos() {
        return this.mantenimientos;
    }
    
    public void setMantenimientos(Set mantenimientos) {
        this.mantenimientos = mantenimientos;
    }




}


